apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cal3hgmee-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cal3hgmee-nodejs 
  name: cal3hgmee-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cal3hgmee-nodejs 
